In [1]:
import numpy as np
# LU Decomposition：
def decmp_lu(A):
    n = A.shape[1]
    A_copy = A.copy()
    inv_L = np.identity(n)
    for i in range(0,n-1):
        for j in range(i+1,n):
            l_coef = A_copy[j][i] / A_copy[i][i]
            A_copy[j] = A_copy[j] - l_coef*A_copy[i]
            E_ji = np.identity(n)
            E_ji[j][i] = -l_coef
            inv_L = np.dot(E_ji, inv_L)
    return inv_L, A_copy # A_copy is the U matrix.

In [2]:
def mask_zero(num): # num is the matrix to be masked:
    if abs(num)<1e-5: #tolerance
        return 0
    return num

In [3]:
# Set a random A matrix and b vector, assuming that Ax = b,
# and use three methods below to find out x:
np.random.seed(42)
A_decmp_test = 5*np.random.randn(5,5)
b_decmp_test = 25*np.random.randn(5,1)
print("Below is the input 5*5 matrix A of Gaussian distribution with mean=0 and sd=5: \r")
print(A_decmp_test)
vfunc_rnd = np.vectorize(lambda x: mask_zero(x))
print("\n")
print("Below is the inversed L after LU decomposistion:\r")
print(vfunc_rnd(decmp_lu(A_decmp_test)[0]))
print("\n")
print("Below is the U after LU decomposistion:\r")
print(vfunc_rnd(decmp_lu(A_decmp_test)[1]))
print("\n")
print("Below is the vector b on the right side of the equation:\r")
print(b_decmp_test)

Below is the input 5*5 matrix A of Gaussian distribution with mean=0 and sd=5: 
[[ 2.48357077 -0.69132151  3.23844269  7.61514928 -1.17076687]
 [-1.17068478  7.89606408  3.83717365 -2.34737193  2.71280022]
 [-2.31708846 -2.32864877  1.20981136 -9.56640122 -8.62458916]
 [-2.81143765 -5.0641556   1.57123666 -4.54012038 -7.06151851]
 [ 7.32824384 -1.1288815   0.33764102 -7.12374093 -2.72191362]]


Below is the inversed L after LU decomposistion:
[[ 1.          0.          0.          0.          0.        ]
 [ 0.47137162  1.          0.          0.          0.        ]
 [ 1.11812482  0.39280741  1.          0.          0.        ]
 [-0.15865311  0.191017   -1.47991094  1.          0.        ]
 [-1.92133913  1.27834411 -4.54408049  4.12207635  1.        ]]


Below is the U after LU decomposistion:
[[ 2.48357077 -0.69132151  3.23844269  7.61514928 -1.17076687]
 [ 0.          7.57019474  5.36368364  1.24219335  2.16093394]
 [ 0.          0.          6.33806478 -1.97377886 -8.86804463]
 [ 0. 

In [4]:
def sub_back(U,c):
    if U.shape[1]!=c.shape[0]:
        return("Wrong Formulation!")
    n = U.shape[1]
    c[n-1][0] = c[n-1][0]/U[n-1][n-1]
    for i in range(n-2, -1, -1):
        for j in range(n-1, i, -1):
            c[i][0] -= U[i][j]*c[j][0]
        c[i][0] = c[i][0]/U[i][i]
    return c

In [5]:
# Method 1: x = np.dot(inv_A, b)
x_inv_test = np.dot(np.linalg.inv(A_decmp_test),b_decmp_test)
x_inv_test

array([[  1.6975399 ],
       [  9.31078437],
       [-14.69889899],
       [  5.09652727],
       [-11.77397147]])

In [6]:
# Method 2: Ax=b -> Ux = c = np.dot(inv_L,b) -> x = np.dot(inv_U,c)
inv_L = vfunc_rnd(decmp_lu(A_decmp_test)[0])
inv_U = np.linalg.inv(vfunc_rnd(decmp_lu(A_decmp_test)[1]))
c_decmp_test = np.dot(inv_L,b_decmp_test)
x_decmp_test = np.dot(inv_U, c_decmp_test)
x_decmp_test

array([[  1.6975399 ],
       [  9.31078437],
       [-14.69889899],
       [  5.09652727],
       [-11.77397147]])

In [7]:
# Method 3: Ax=b -> Ux = c = np.dot(inv_L,b) -> x = sub_back(U,c)
U_sub_back_test = vfunc_rnd(decmp_lu(A_decmp_test)[1])
c_sub_back_test = c_decmp_test
sub_back(U_sub_back_test,c_sub_back_test)

array([[  1.6975399 ],
       [  9.31078437],
       [-14.69889899],
       [  5.09652727],
       [-11.77397147]])